#!/bin/bash


mkdir -p build

cd build

/usr/local/bin/cmake -DGRPC_AS_SUBMODULE=1 \
  -DCMAKE_EXPORT_COMPILE_COMMANDS=1 \
  -DCMAKE_BUILD_TYPE=DEBUG .. \
  -DEVENT__DISABLE_MBEDTLS=ON \
  && make -j12 \
  && cp ./compile_commands.json ..

